---
vars:
  machine_type: n1-standard-1 # default
  image: ubuntu-1404-trusty-v20171115a
  service_account_email: nik-68@coherent-bay-160809.iam.gserviceaccount.com 
  credentials_file: /home/nkhlpathak/git/ansible/nik.json
  project_id: coherent-bay-160809
  network: nik
  subnetwork: public
- name: Create custom boot disk
  gce_pd:
         name: "{{ instance_name }}"
         image: "{{ instance_image }}"
         size_gb: "{{ disk_size }}"
         zone: "{{ zone  }"
- name: Create instance(s)
  hosts: localhost
  gather_facts: no
  connection: local

    tasks:
    - name: Launch instances
      gce:
          instance_names: test
          machine_type: "{{ machine_type }}"
          image: "{{ image }}"
          service_account_email: "{{ service_account_email }}"
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          network: "{{ network }}"
          subnetwork: "{{ subnetworks }}"
          tags: public
      register: gce

