---
- name: Create gce snapshot
  hosts: localhost
  tasks:
   - name: Creaing Snap
     gce_snapshot:
      instance_name: web-on-buckets
      snapshot_name: changes
      state: present
      service_account_email: sql-buckets@coherent-bay-160809.iam.gserviceaccount.com
      credentials_file: /home/nkhlpathak/git/ansible/nik.json
      project_id: coherent-bay-160809
   - name: Create disk from snapshot
     gce_pd:
          disk_type: pd-standard
          snapshot: changes
          name: changes-disk
          state: present
          zone:  asia-east1-a
          size_gb: 30 
          service_account_email: sql-buckets@coherent-bay-160809.iam.gserviceaccount.com
          credentials_file: /home/nkhlpathak/git/ansible/nik.json
          project_id: coherent-bay-160809
   - gce_img:
      name: changes-img
      source: changes-disk
      zone: asia-east1-a
      state: present
      service_account_email: sql-buckets@coherent-bay-160809.iam.gserviceaccount.com
      pem_file: /home/nkhlpathak/git/ansible/nik.json
      project_id: coherent-bay-160809
   - name: Create Temp
     gce_instance_template:
      name: changes-temp
      size: n1-standard-1
      state: present 
      service_account_email: sql-buckets@coherent-bay-160809.iam.gserviceaccount.com
      credentials_file: /home/nkhlpathak/git/ansible/nik.json
      project_id: coherent-bay-160809
      subnetwork_region: asia-east1
      network: nikhil
      subnetwork: public
      tags: public
      disks_gce_struct:
        - device_name: /dev/sda
          boot: true
          autoDelete: true
          initializeParams:
             diskSizeGb: 30
             diskType: pd-ssd
             sourceImage:  projects/coherent-bay-160809/global/images/changes-img
   - name: Update MIG with Autoscaler
     gce_mig:
      name: changes-auto
      zone: asia-east1-a
      state: present 
      service_account_email: sql-buckets@coherent-bay-160809.iam.gserviceaccount.com
      credentials_file: /home/nkhlpathak/git/ansible/nik.json
      project_id: coherent-bay-160809
      size: 2
      template: changes-temp
      recreate_instances: yes
      autoscaling:
        enabled: yes
        name: my-changes
        policy:
          min_instances: 2
          max_instances: 5
          cool_down_period: 37
          cpu_utilization:
            target: .39
          load_balancing_utilization:
            target: 0.4
