---
- name: Create gce snapshot
  hosts: localhost
  tasks:
   - name: Creaing Snap
     gce_snapshot:
      instance_name: nginx-pokermagnet
      snapshot_name: enngu
      state: present
      service_account_email: use-ansible@robotic-pact-170607.iam.gserviceaccount.com
      credentials_file: /home/dev_ops/git/ansible/nik.json
      project_id: robotic-pact-170607 
   - name: Create disk from snapshot
     gce_pd:
          disk_type: pd-standard
          snapshot: enngu
          name: enngu-disk
          state: present
          zone:  asia-east1-a
          size_gb: 15 
          service_account_email: use-ansible@robotic-pact-170607.iam.gserviceaccount.com
          credentials_file: /home/dev_ops/git/ansible/nik.json
          project_id: robotic-pact-170607
   - gce_img:
      name: enngu-img
      source: enngu-disk
      zone: asia-east1-a
      state: present
      service_account_email: use-ansible@robotic-pact-170607.iam.gserviceaccount.com
      pem_file: /home/dev_ops/git/ansible/nik.json
      project_id: robotic-pact-170607
   - name: Create Temp
     gce_instance_template:
      name: enngu-temp
      size: n1-standard-1
      state: present 
      service_account_email: use-ansible@robotic-pact-170607.iam.gserviceaccount.com
      credentials_file: /home/dev_ops/git/ansible/nik.json
      project_id: robotic-pact-170607
      subnetwork_region: asia-east1
      network: vpc-mega
      subnetwork: public
      tags: ai
      disks_gce_struct:
        - device_name: /dev/sda
          boot: true
          autoDelete: true
          initializeParams:
             diskSizeGb: 30
             diskType: pd-ssd
             sourceImage:  projects/robotic-pact-170607/global/images/enngu-img
   - name: Update MIG with Autoscaler
     gce_mig:
      name: enngu-auto
      zone: asia-east1-a
      state: present 
      service_account_email: use-ansible@robotic-pact-170607.iam.gserviceaccount.com
      credentials_file: /home/dev_ops/git/ansible/nik.json
      project_id: robotic-pact-170607
      size: 2
      template: enngu-temp
      recreate_instances: yes
      autoscaling:
        enabled: yes
        name: my-enngu
        policy:
          min_instances: 2
          max_instances: 5
          cool_down_period: 70
          cpu_utilization:
            target: .79
          load_balancing_utilization:
            target: 0.7
